# Generated by Django 5.0.1 on 2024-01-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hname', models.CharField(max_length=100)),
                ('gen', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('num', models.CharField(max_length=20)),
                ('rent', models.CharField(max_length=20)),
                ('img1', models.ImageField(upload_to='static/image')),
                ('img2', models.ImageField(upload_to='static/image')),
                ('img3', models.ImageField(upload_to='static/image')),
                ('img4', models.ImageField(upload_to='static/image')),
            ],
        ),
    ]
