# Generated by Django 5.0.1 on 2024-01-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdial', '0002_hostel_city_hostel_rbad1_hostel_rbad3_hostel_rbad4'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='rbad2',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
