# Generated by Django 5.0.1 on 2024-01-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdial', '0003_hostel_rbad2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='ac',
            field=models.CharField(choices=[('Spacious Cupboard', 'Spacious Cupboard'), ('Not Spacious Cupboard', 'Not Spacious Cupboard')], default='Spacious Cupboard', max_length=100, verbose_name='Amenities'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='am',
            field=models.CharField(choices=[('Attached Washroom', 'Attached Washroom'), ('Not Attached Washroom', 'Not Attached Washroom')], default='Attached Washroom', max_length=100, verbose_name='Amenities'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='ser1',
            field=models.CharField(default='Spacious Refrigerator', max_length=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='ser2',
            field=models.CharField(default='Washing Machine', max_length=100),
        ),
        migrations.AddField(
            model_name='hostel',
            name='ser3',
            field=models.CharField(default='Hot Water Supply', max_length=100),
        ),
    ]
